navsim_log_path: ${oc.env:OPENSCENE_DATA_ROOT}/navsim_logs/${train_test_split.data_split} # path to log annotations
sensor_blobs_path: ${oc.env:OPENSCENE_DATA_ROOT}/sensor_blobs/${train_test_split.data_split} # path to sensor blobs
synthetic_scenes_path: ${oc.env:OPENSCENE_DATA_ROOT}/synthetic_scenes # path to synthetic scenes
metric_cache_path: ${oc.env:NAVSIM_EXP_ROOT}/metric_cache # path to metric cache